// BSG Newlib File System Initialization
//
// Autogenerated by bsg_newlib_mkfs utility

#include <sys/types.h>
#include <machine/lfs.h>
#include <machine/lfs_bd.h>

// LFS configuration
struct lfs_config bsg_newlib_fs_cfg = {
    // block device operations: lfs_bd.h
    .read  = lfs_read,
    .prog  = lfs_prog,
    .erase = lfs_erase,
    .sync  = lfs_sync,

    // block device default configuration
    .read_size   = 32,
    .prog_size   = 32,
    .block_size  = 128,
    .block_count = 64,
    .lookahead   = 32
};

uint8_t lfs_mem[] = {};